
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar/Navbar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Inicio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <div>
        <body className={inter.className}>
          <main>
            <Navbar />
          </main>
          {children}
        </body>
        <footer className="bg-gray-800 p-4 text-center text-white">
          &copy; 2024 Mi Sitio
        </footer>
      </div>
    </html >
  );
}
